[install]
is_configured = false
state = enabled

[ui]
is_visible = 1
label = ActionStack

[launcher]
author = ActionStack
version = 0.5.1
description = Role-aware forms and reliable event submission to Splunk SOAR.

[package]
id = splunk_actionstack

[shclustering]
deployer_push_mode = full
