[capability::actionstack_use]
[capability::actionstack_submit]
[capability::actionstack_read_team]
[capability::actionstack_edit]
[capability::actionstack_publish]
[capability::actionstack_admin]
[capability::actionstack_audit]

[role_user]
actionstack_use = enabled
actionstack_submit = enabled

[role_admin]
actionstack_use = enabled
actionstack_submit = enabled
actionstack_read_team = enabled
actionstack_edit = enabled
actionstack_publish = enabled
actionstack_admin = enabled
actionstack_audit = enabled
